name: accompagnateur
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  encrypt: ^5.0.3
  animated_text_kit: ^4.2.2
  audio_waveforms: ^1.0.4
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  audioplayers: ^6.0.0
  super_tooltip: ^2.0.7
  record: ^5.0.5
  image_picker: ^1.0.8
  video_player: ^2.8.6
  path: ^1.9.0
  get_thumbnail_video: ^0.7.3
  auto_size_text: ^3.0.0
  jwt_decoder: ^2.0.1
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^6.0.3
  workmanager: ^0.5.2
  http: ^1.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.4.0
  file_picker: ^9.0.2
  flutter_launcher_icons: ^0.14.3
  photo_manager: ^3.2.2
  bottom_navbar_with_indicator: ^0.0.9
  wechat_assets_picker: ^9.2.1
  flutter_downloader: ^1.11.8
  device_info_plus: ^11.3.0
  flutter_pdfview: ^1.3.2
  image: ^4.2.0
  http_parser: ^4.0.2
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  objectbox_generator: ^4.1.0




flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/launch_logo.png"




